### ISSUE TITLE
How to host a camera

### ISSUE THREAD

**Issue by micdenny** [donovan6000/M33-Fio#214]
I saw the settings here:

![image](https://cloud.githubusercontent.com/assets/1633595/23921674/cc228a4a-08ff-11e7-835b-68450f1575a5.png)

but after I save and reboot octoprint I can't see anything on http://localhost:4999/snapshot.jpg

Have I missed a step?

**Comment by donovan6000** [comment]
Hosting a camera should just work as soon as you enable that setting. It automatically configures OctoPrint's settings to use the URLs that it hosts, and you should be able to verify that it's all working by testing the URLs in OctoPrint's Settings > Webcam & Timelapse tab.

You can also try out the newest version, [V1.18](https://github.com/donovan6000/M33-Fio/releases/tag/V1.18), and let me know if your still having this issue. There was an issue with the camera hosting on macOS Sierra that was fixed.

**Comment by micdenny** [comment]
I simply configured octopi setting the right property for my cam and now I can see the camera, but without using this M33-Fio feature, that I still don't understand what it adds, it simply helps you configure octoprint settings? I just did this: https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

**Comment by donovan6000** [comment]
M33 Fio is capable of hosting the webcam stream and snapshot itself without having to use any other programs, like mjpg-streamer.

Does running the following show any errors?
```
wget https://raw.githubusercontent.com/donovan6000/M33-Fio/master/octoprint_m33fio/webcam_server.py
python webcam_server.py
```

**Comment by micdenny** [comment]
> M33 Fio is capable of hosting the webcam stream and snapshot itself without having to use any other programs, like mjpg-streamer.

thank you for the explanation, now it's clear.

> Does running the following show any errors?

I will test it and let you know.

**Comment by donovan6000** [comment]
It's been a while since anyone has responded to this issue, so I'll probably close it in a couple of days. Let me know if you still have any interest in testing/fixing this issue.

**Comment by micdenny** [comment]
Testing now, sorry...

**Comment by micdenny** [comment]
@donovan6000 I don't see the above screenshot anymore with the new version, I only see this menu:

![image](https://cloud.githubusercontent.com/assets/1633595/26730384/0dbedb44-47b1-11e7-88bd-7432ecf8b641.png)

**Comment by micdenny** [comment]
> Does running the following show any errors?

I get this error:

![image](https://cloud.githubusercontent.com/assets/1633595/26731185/8241c452-47b3-11e7-9cb8-7402075edd3d.png)

```
pi@octopi:~ $ python webcam_server.py
Traceback (most recent call last):
  File "webcam_server.py", line 19, in <module>
    from PIL import Image
ImportError: No module named PIL
```

**Comment by micdenny** [comment]
I did this `sudo apt-get install python-imaging` and now the error is:

```
pi@octopi:~ $ python webcam_server.py
Traceback (most recent call last):
  File "webcam_server.py", line 20, in <module>
    import pygame.camera
ImportError: No module named pygame.camera
```

**Comment by micdenny** [comment]
I did also `sudo apt-get install python-pygame` and now I get this, so it seems to work:

```
pi@octopi:~ $ python webcam_server.py
Using webcam device /dev/video0 with a resolution of 640x480 running at 20 frames/second
Hosting webcam still image at http://192.168.50.161:4999/snapshot.jpg
Hosting webcam video stream at http://192.168.50.161:4999/stream.mjpg
```

now I check the portal

**Comment by micdenny** [comment]
but I can't see from the site where to find the menu to activate the cam anymore

**Comment by donovan6000** [comment]
The menu is in M33 Fio's settings

**Comment by micdenny** [comment]
I don't see it, what could be the reason? Do you check if there's a webcam to show the options?

**Comment by donovan6000** [comment]
[M33 Fio checks if a camera is connected and all required libraries are installed](https://github.com/donovan6000/M33-Fio/blob/master/octoprint_m33fio/__init__.py#L6074-L6092) before showing the camera options. I wonder how you managed to see it before when you didn't had pygame and pillow installed though.

**Comment by micdenny** [comment]
> M33 Fio checks if a camera is connected and all required libraries are installed before showing the camera options.

first question is why I had to install pygame manually?

> I wonder how you managed to see it before when you didn't had pygame and pillow installed though.

I wonder me too, probably something went mad after I upgraded to a new version of octopi, then I had to install a custom version of M33 from one of the maintainers of octopi to let the M33 plugin work again, then you released the compatible version and I installed your official distribution, and I think at the time I installed the custom M33 version or lately your official version the menu disappeared.

I'm quite confused right now, I think it is better to backup my octopi device, and start from scratch and see if everything works as expected or not.

**Comment by donovan6000** [comment]
There were too many problems with automatically installing the requirements for M33 Fio's camera features and I didn't want people to have any problems installing M33 Fio, so that's why it's necessary to manually install the camera dependencies in order to use it.

Let me know if starting from scratch fixed the issue.

**Comment by donovan6000** [comment]
It's been a while since anyone has responded to this issue, so I'll probably close it in a couple of days. Let me know if you still have any interest in testing/fixing this issue.
